[versions]
agp = "8.13.2"
kotlin = "2.3.0"
androidx-appcompat = "1.7.1"
androidx-compose-bom = "2025.12.01"
androidx-compose-material3 = "1.4.0"
androidx-compose-ui-tooling = "1.10.0"
androidx-navigation3 = "1.0.0"
androidx-preference = "1.2.1"
danlew-joda = "2.14.0"
kotlinx-serialization-json = "1.9.0"
google-material = "1.13.0"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "androidx-compose-ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "androidx-compose-ui-tooling" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "androidx-navigation3" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "androidx-navigation3" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "androidx-preference" }
danlew-joda = { group = "net.danlew", name = "android.joda", version.ref = "danlew-joda" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
